/* assets_preshift.h - pre-shifted (sub 0..3) entity sprites.
 * Generated by gen_preshift.py from assets.c. (c) 2016 dir3kt/jlauener, MIT.
 * Format: [w,h,wb2,nframes, for s0..3: for frame: for row: wb2 data, wb2 mask]. */
#ifndef ASSETS_PRESHIFT_H
#define ASSETS_PRESHIFT_H

extern const unsigned char entity_skeleton_plus_mask_ps[];
extern const unsigned char entity_skeleton_plus_mask_ps_desc[6];
extern const unsigned char entity_skull_plus_mask_ps[];
extern const unsigned char entity_skull_plus_mask_ps_desc[6];
extern const unsigned char entity_bird_plus_mask_ps[];
extern const unsigned char entity_bird_plus_mask_ps_desc[6];
extern const unsigned char entity_hurler_plus_mask_ps[];
extern const unsigned char entity_hurler_plus_mask_ps_desc[6];
extern const unsigned char entity_bone_plus_mask_ps[];
extern const unsigned char entity_bone_plus_mask_ps_desc[6];
extern const unsigned char entity_skeleton_armored_plus_mask_ps[];
extern const unsigned char entity_skeleton_armored_plus_mask_ps_desc[6];
extern const unsigned char entity_fireball_horiz_plus_mask_ps[];
extern const unsigned char entity_fireball_horiz_plus_mask_ps_desc[6];
extern const unsigned char entity_fireball_vert_plus_mask_ps[];
extern const unsigned char entity_fireball_vert_plus_mask_ps_desc[6];

/* player sprites live in ROM bank 1 (64k build) */
extern const unsigned char player_plus_mask_ps[];
extern const unsigned char player_plus_mask_ps_desc[6];
extern const unsigned char player_attack_left_plus_mask_ps[];
extern const unsigned char player_attack_left_plus_mask_ps_desc[6];
extern const unsigned char player_attack_right_plus_mask_ps[];
extern const unsigned char player_attack_right_plus_mask_ps_desc[6];

#endif /* ASSETS_PRESHIFT_H */
