/* assets.h - CastleBoy art (Supervision 2bpp) + maps. (c) 2016 dir3kt/jlauener, MIT.
 * Generated by gen_assets.py. 2bpp row-major; opaque or +mask. */
#ifndef ASSETS_H
#define ASSETS_H

extern const unsigned char tileset[];
extern const unsigned char background_mountain[];
extern const unsigned char logo[];
extern const unsigned char player_plus_mask[];
extern const unsigned char player_attack_left_plus_mask[];
extern const unsigned char player_attack_right_plus_mask[];
extern const unsigned char entity_candle_plus_mask[];
extern const unsigned char entity_coin_plus_mask[];
extern const unsigned char entity_knife_plus_mask[];
extern const unsigned char entity_skeleton_plus_mask[];
extern const unsigned char entity_skull_plus_mask[];
extern const unsigned char entity_bird_plus_mask[];
extern const unsigned char entity_hurler_plus_mask[];
extern const unsigned char entity_bone_plus_mask[];
extern const unsigned char entity_skeleton_armored_plus_mask[];
extern const unsigned char entity_fireball_horiz_plus_mask[];
extern const unsigned char entity_fireball_vert_plus_mask[];
extern const unsigned char entity_falling_platform_plus_mask[];
extern const unsigned char entity_moving_platform_plus_mask[];
extern const unsigned char entity_candlestick_plus_mask[];
extern const unsigned char ui_hp_full[];
extern const unsigned char ui_hp_empty[];
extern const unsigned char ui_knife_count[];
extern const unsigned char font[];
extern const unsigned char stage_1_1[];
extern const unsigned char stage_1_2[];
extern const unsigned char stage_1_3[];

#endif /* ASSETS_H */
