#!/usr/bin/env python3
# gen_assets.py - convert CastleBoy art (Arduboy 1bpp vertical-page) into
# Supervision 2bpp row-major data, so the world can be blitted with byte copies
# and DMA'd to VRAM (no per-pixel software shifting of the whole screen).
# Source data (c) 2016 dir3kt / jlauener, MIT License (see LICENSE.castleboy).
#
# 2bpp packing: leftmost pixel = low bits; shade 0(00)=white(lit), 3(11)=black.
# Sheet format emitted:
#   opaque:  [w, h, frames * (h rows * wb data bytes)]
#   masked:  [w, h, frames * (h rows * (wb data bytes + wb mask bytes))]
#   wb = ceil(w/4); mask 2bpp: 0x3 per opaque pixel, 0x0 transparent.
import re, os

# Path to the original CastleBoy assets.h (Arduboy source data). Override with
# the CASTLEBOY_ASSETS env var; defaults to the upstream checkout location.
ASRC_PATH = os.environ.get('CASTLEBOY_ASSETS',
                           '/home/claude/CastleBoy/CastleBoy/assets.h')
ASRC = open(ASRC_PATH).read()

def get_array(name):
    m = re.search(r'const uint8_t %s\[\]\s*=\s*\{(.*?)\};' % re.escape(name), ASRC, re.S)
    if not m: raise KeyError(name)
    body = re.sub(r'//[^\n]*', '', m.group(1))
    return [int(t.strip(), 0) & 0xFF for t in body.split(',') if t.strip()]

def decode_overwrite(arr):
    w, h = arr[0], arr[1]
    pages = (h + 7) // 8
    fsize = w * pages
    nf = (len(arr) - 2) // fsize
    frames = []
    for f in range(nf):
        lit = [[0]*w for _ in range(h)]
        base = 2 + f*fsize
        for p in range(pages):
            for cx in range(w):
                b = arr[base + p*w + cx]
                for bit in range(8):
                    y = p*8 + bit
                    if y < h: lit[y][cx] = (b >> bit) & 1
        frames.append((lit, None))
    return w, h, frames

def decode_plusmask(arr):
    w, h = arr[0], arr[1]
    pages = (h + 7) // 8
    fsize = w * pages * 2
    nf = (len(arr) - 2) // fsize
    frames = []
    for f in range(nf):
        lit = [[0]*w for _ in range(h)]
        vis = [[0]*w for _ in range(h)]
        base = 2 + f*fsize
        for p in range(pages):
            for cx in range(w):
                d = arr[base + (p*w+cx)*2]
                m = arr[base + (p*w+cx)*2 + 1]
                for bit in range(8):
                    y = p*8 + bit
                    if y < h:
                        lit[y][cx] = (d >> bit) & 1
                        vis[y][cx] = (m >> bit) & 1
        frames.append((lit, vis))
    return w, h, frames

def pack(w, h, frames, masked):
    wb = (w + 3) // 4
    out = [w, h]
    for (lit, vis) in frames:
        for row in range(h):
            for bx in range(wb):
                val = 0
                for i in range(4):
                    px = bx*4 + i
                    l = lit[row][px] if px < w else 0
                    val |= (0 if l else 3) << (i*2)
                out.append(val)
            if masked:
                for bx in range(wb):
                    mval = 0
                    for i in range(4):
                        px = bx*4 + i
                        v = (vis[row][px] if vis is not None else 1) if px < w else 0
                        mval |= (3 if v else 0) << (i*2)
                    out.append(mval)
    return out

OPAQUE = [('tileset','tileset'), ('background_mountain','background_mountain'), ('logo','logo')]
MASKED_PM = [
    'player_plus_mask','player_attack_left_plus_mask','player_attack_right_plus_mask',
    'entity_candle_plus_mask','entity_coin_plus_mask','entity_knife_plus_mask',
    'entity_skeleton_plus_mask','entity_skull_plus_mask','entity_bird_plus_mask',
    'entity_hurler_plus_mask','entity_bone_plus_mask','entity_skeleton_armored_plus_mask',
    'entity_fireball_horiz_plus_mask','entity_fireball_vert_plus_mask',
    'entity_falling_platform_plus_mask','entity_moving_platform_plus_mask',
    'entity_candlestick_plus_mask',
]
SELFMASK = ['ui_hp_full','ui_hp_empty','ui_knife_count','font']
MAPS = ['stage_1_1','stage_1_2','stage_1_3']

def emit(name, data, fc):
    fc.write("const unsigned char %s[] = {" % name)
    for i, b in enumerate(data):
        if i % 16 == 0: fc.write("\n  ")
        fc.write("0x%02X," % b)
    fc.write("\n};\n\n")

hdr = open('assets.h','w'); src = open('assets.c','w')
hdr.write("/* assets.h - CastleBoy art (Supervision 2bpp) + maps. (c) 2016 dir3kt/jlauener, MIT.\n")
hdr.write(" * Generated by gen_assets.py. 2bpp row-major; opaque or +mask. */\n")
hdr.write("#ifndef ASSETS_H\n#define ASSETS_H\n\n")
src.write("/* assets.c - generated 2bpp data (c) 2016 dir3kt/jlauener, MIT. */\n#include \"assets.h\"\n\n")
total = 0
for emitname, srcname in OPAQUE:
    w,h,fr = decode_overwrite(get_array(srcname))
    d = pack(w, h, fr, False)
    total += len(d); hdr.write("extern const unsigned char %s[];\n"%emitname); emit(emitname, d, src)
for name in MASKED_PM:
    w,h,fr = decode_plusmask(get_array(name))
    d = pack(w, h, fr, True)
    total += len(d); hdr.write("extern const unsigned char %s[];\n"%name); emit(name, d, src)
for name in SELFMASK:
    w,h,fr = decode_overwrite(get_array(name))
    fr2 = [(lit, [[lit[y][x] for x in range(w)] for y in range(h)]) for (lit,_) in fr]
    d = pack(w, h, fr2, True)
    total += len(d); hdr.write("extern const unsigned char %s[];\n"%name); emit(name, d, src)
for name in MAPS:
    d = get_array(name)
    total += len(d); hdr.write("extern const unsigned char %s[];\n"%name); emit(name, d, src)
hdr.write("\n#endif /* ASSETS_H */\n"); hdr.close(); src.close()
print("2bpp assets written, total bytes:", total)
