#!/usr/bin/env python3
# gen_preshift.py - generate pre-shifted (sub-pixel 0..3) copies of the entity
# +mask sprites straight from the already-converted assets.c, so the enemy
# blitter can draw with byte-aligned masked ORs (no per-byte variable shift).
#
# Reads assets.c, writes assets_preshift.h / assets_preshift.c.
#
# 2bpp packing matches assets.c: leftmost pixel = low 2 bits; shade 3 = black.
# Output sheet format (per sprite):
#   [w, h, wb2, nframes,
#    for s in 0..3: for f in 0..nframes-1: for row in 0..h-1:
#        wb2 data bytes, then wb2 mask bytes ]
#   wb2 = ceil(w/4) + 1  (one extra byte absorbs the <=3px shift spill)
import re

SRC = open('assets.c').read()

# Moving combat enemies that are the most-often-on-screen per-frame blits and
# benefit most from removing the variable sub-pixel shift. Candles are drawn as
# background; pickups/platforms/fx stay on the generic shifting blit to save ROM.
SPRITES = [
    'entity_skeleton_plus_mask','entity_skull_plus_mask','entity_bird_plus_mask',
    'entity_hurler_plus_mask','entity_bone_plus_mask','entity_skeleton_armored_plus_mask',
    'entity_fireball_horiz_plus_mask','entity_fireball_vert_plus_mask',
]

# Player sprites are large (~14KB pre-shifted); in the 64k build they live in a
# switchable ROM bank (BANK1SEG) accessed only by the fixed-resident player blit.
PLAYER_SPRITES = [
    'player_plus_mask','player_attack_left_plus_mask','player_attack_right_plus_mask',
]

def get_bytes(name):
    m = re.search(r'const unsigned char %s\[\]\s*=\s*\{(.*?)\};' % re.escape(name), SRC, re.S)
    if not m: raise KeyError(name)
    return [int(t, 0) & 0xFF for t in re.findall(r'0x[0-9A-Fa-f]+', m.group(1))]

def decode(b):
    """-> w,h,frames; each frame = (data[h][wb], mask[h][wb])"""
    w, h = b[0], b[1]; wb = (w + 3) // 4; fsize = h * wb * 2
    nf = (len(b) - 2) // fsize
    frames = []
    for f in range(nf):
        base = 2 + f * fsize
        data = []; mask = []
        for r in range(h):
            ro = base + r * wb * 2
            data.append(b[ro:ro+wb])
            mask.append(b[ro+wb:ro+wb*2])
        frames.append((data, mask))
    return w, h, wb, frames

def row_to_pixels(row_bytes, wb):
    """unpack wb bytes -> list of 4*wb 2-bit pixels (index 0 = leftmost)."""
    px = []
    for by in row_bytes:
        for i in range(4):
            px.append((by >> (i*2)) & 3)
    return px

def pixels_to_bytes(px, wb2):
    out = []
    for bx in range(wb2):
        v = 0
        for i in range(4):
            idx = bx*4 + i
            p = px[idx] if idx < len(px) else 0
            v |= (p & 3) << (i*2)
        out.append(v)
    return out

def preshift(name):
    b = get_bytes(name)
    w, h, wb, frames = decode(b)
    wb2 = wb + 1
    out = [w, h, wb2, len(frames)]
    for s in range(4):                    # sub-pixel shift 0..3
        for (data, mask) in frames:
            for r in range(h):
                dpx = row_to_pixels(data[r], wb)
                mpx = row_to_pixels(mask[r], wb)
                # shift right by s pixels (insert s transparent pixels at left)
                dpx = [0]*s + dpx
                mpx = [0]*s + mpx
                out += pixels_to_bytes(dpx, wb2)
                out += pixels_to_bytes(mpx, wb2)
    return w, h, wb2, len(frames), out

def emit(name, data, fc):
    fc.write("const unsigned char %s_ps[] = {" % name)
    for i, x in enumerate(data):
        if i % 16 == 0: fc.write("\n  ")
        fc.write("0x%02X," % x)
    fc.write("\n};\n\n")

hdr = open('assets_preshift.h', 'w')
src = open('assets_preshift.c', 'w')
hdr.write("/* assets_preshift.h - pre-shifted (sub 0..3) entity sprites.\n")
hdr.write(" * Generated by gen_preshift.py from assets.c. (c) 2016 dir3kt/jlauener, MIT.\n")
hdr.write(" * Format: [w,h,wb2,nframes, for s0..3: for frame: for row: wb2 data, wb2 mask]. */\n")
hdr.write("#ifndef ASSETS_PRESHIFT_H\n#define ASSETS_PRESHIFT_H\n\n")
def emit_desc(name, w, h, wb2, nf, fc):
    # 6-byte descriptor: {w, h, wb2, nframes, stride, framebytes}
    # stride = wb2*2 (bytes/row incl. mask), framebytes = h*stride (one frame).
    # Precomputed here so the per-sprite setup needs at most one runtime multiply.
    stride = wb2 * 2
    framebytes = h * stride           # <= 16*10 = 160, fits a byte
    assert framebytes <= 255, (name, framebytes)
    fc.write("const unsigned char %s_ps_desc[6] = { %d,%d,%d,%d,%d,%d };\n"
             % (name, w, h, wb2, nf, stride, framebytes))

src.write("/* assets_preshift.c - generated pre-shifted entity sprites. */\n#include \"assets_preshift.h\"\n\n")

# non-banked descriptors {w,h,wb2,nframes} - stay in normal RODATA so the banked
# blit setup can read them with bank 0 mapped (the banked header is unreadable
# while bank 1/2 is mapped).
ent_meta = []
for name in SPRITES:
    w, h, wb2, nf, data = preshift(name)
    ent_meta.append((name, w, h, wb2, nf, data))
    hdr.write("extern const unsigned char %s_ps[];\n" % name)
    hdr.write("extern const unsigned char %s_ps_desc[6];\n" % name)
for (name, w, h, wb2, nf, data) in ent_meta:
    emit_desc(name, w, h, wb2, nf, src)
src.write("\n")

# the bulk pre-shifted enemy pixel data goes in ROM bank 2 (64k build).
src.write("#ifdef CB_BANKED\n#pragma rodata-name (push, \"BANK2SEG\")\n#endif\n\n")
total = 0
for (name, w, h, wb2, nf, data) in ent_meta:
    total += len(data)
    emit(name, data, src)
src.write("#ifdef CB_BANKED\n#pragma rodata-name (pop)\n#endif\n")

# player sprites: declared in the same header, data emitted into a separate .c
# placed in ROM bank 1; descriptors live in normal RODATA (in this file).
hdr.write("\n/* player sprites live in ROM bank 1 (64k build) */\n")
pl_meta = []
for name in PLAYER_SPRITES:
    w, h, wb2, nf, data = preshift(name)
    pl_meta.append((name, w, h, wb2, nf, data))
    hdr.write("extern const unsigned char %s_ps[];\n" % name)
    hdr.write("extern const unsigned char %s_ps_desc[6];\n" % name)
src.write("\n/* player descriptors (non-banked) */\n")
for (name, w, h, wb2, nf, data) in pl_meta:
    emit_desc(name, w, h, wb2, nf, src)
hdr.write("\n#endif /* ASSETS_PRESHIFT_H */\n")
hdr.close(); src.close()

pl = open('assets_player_ps.c', 'w')
pl.write("/* assets_player_ps.c - pre-shifted PLAYER sprite pixel data, ROM bank 1.\n")
pl.write(" * Generated by gen_preshift.py from assets.c. (c) 2016 dir3kt/jlauener, MIT. */\n")
pl.write("#include \"assets_preshift.h\"\n\n")
pl.write("#pragma rodata-name (push, \"BANK1SEG\")\n\n")
ptotal = 0
for (name, w, h, wb2, nf, data) in pl_meta:
    ptotal += len(data)
    emit(name, data, pl)
pl.write("#pragma rodata-name (pop)\n")
pl.close()
print("pre-shifted entity bytes:", total, " player(bank1) bytes:", ptotal)
